//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.14 at 12:36:57 AM IST 
//


package com.trabeya.bank_integration.accounts;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.trabeya.bank_integration.accounts package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.trabeya.bank_integration.accounts
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAccountRequest }
     * 
     */
    public GetAccountRequest createGetAccountRequest() {
        return new GetAccountRequest();
    }

    /**
     * Create an instance of {@link GetAccountResponse }
     * 
     */
    public GetAccountResponse createGetAccountResponse() {
        return new GetAccountResponse();
    }

    /**
     * Create an instance of {@link Account }
     * 
     */
    public Account createAccount() {
        return new Account();
    }

    /**
     * Create an instance of {@link GetTotalAmountRequest }
     * 
     */
    public GetTotalAmountRequest createGetTotalAmountRequest() {
        return new GetTotalAmountRequest();
    }

    /**
     * Create an instance of {@link GetTotalAmountResponse }
     * 
     */
    public GetTotalAmountResponse createGetTotalAmountResponse() {
        return new GetTotalAmountResponse();
    }

    /**
     * Create an instance of {@link OwnFundTransfer }
     * 
     */
    public OwnFundTransfer createOwnFundTransfer() {
        return new OwnFundTransfer();
    }

    /**
     * Create an instance of {@link OwnFundTransferResponse }
     * 
     */
    public OwnFundTransferResponse createOwnFundTransferResponse() {
        return new OwnFundTransferResponse();
    }

    /**
     * Create an instance of {@link OtherFundTransfer }
     * 
     */
    public OtherFundTransfer createOtherFundTransfer() {
        return new OtherFundTransfer();
    }

    /**
     * Create an instance of {@link OtherFundTransferResponse }
     * 
     */
    public OtherFundTransferResponse createOtherFundTransferResponse() {
        return new OtherFundTransferResponse();
    }

}
